apiVersion: v1alpha
kind: cypress
showconsolelog: false
sauce:
  region: us-west-1
  metadata:
    name: Testing Cypress Support
    tags:
    - e2e
    - release team
    - other tag
    build: Release $CI_COMMIT_SHORT_SHA
cypress:
  configFile: ./cypress.json
suites:
- name: saucy test
  browser: chrome
  config:
    testFiles:
    - '**/*.*'
    env:
      hello: world
docker:
  fileTransfer: mount
  image:
    name: saucelabs/stt-cypress-mocha-node
    tag: v0.3.3